site_name: My Docs
theme:
  name: material
  language: da
  palette:
    primary: indigo
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.prune
    - navigation.top
  icon:
    repo: fontawesome/brands/git-alt
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.betterem
extra:
  status:
    new: Recently added
copyright: Copyright &copy; 2022 Mathias Jacobsen
repo_url: https://github.com/mathzb/baungrd-docs
repo_name: mathzb/baungrd-docs
edit_uri: edit/main/docs/